
<div class="page-header">
    <h2><?=$this->vars['title']?></h2>
    <small>С помощью данного раздела Вы сможете добавлять, удалять и редактировать <?=mb_strtolower($this->vars['title'],'utf-8')?>.</small>
</div>
<?$countAll=count($this->vars['description']);?>

<div id="addforms" class="forms"></div>
<a class="add" href="javascript:addDesc('<?php echo $this->vars['objects'];?>');">Добавить</a>

<?php echo $this->vars['paging']?>
<table class="table table-striped table-bordered table-condensed">
	<thead>
        <tr>
		    <th width="10%"></th>
            <th width="25%" style="text-align: center;">Название</th>
            <th width="65%" style="text-align: center;">Описание</th>
            <th width="10%"></th>
        </tr>
		<?if($countAll>0):?>
			<tbody>
				<?php $i=0; while($i<$countAll) :?>
					<tr id="desc_<?php echo $this->vars['description'][$i]['id'];?>">
					    <td style="text-align: center;"><img class="link" title="Редактировать" onclick="upDescription(<?php echo "'".$this->vars['objects']."'";?>,<?php echo $this->vars['description'][$i]['id'];?>);" src="/admin_tpl/images/b_edit.png"></td>
						<td style="text-align: center;"><?php echo $this->vars['description'][$i]['name'];?></td>
						<td style="text-align: center;">
							<?php echo substr(strip_tags($this->vars['description'][$i]['desc']),0,200);?> ... <span id="link_<?php echo $this->vars['description'][$i]['id'];?>"><a href="javascript:more('<?php echo $this->vars['objects'];?>',<?php echo $this->vars['description'][$i]['id'];?>);"> Смотреть</a></span>
						</td>
						<td style="text-align: center;">
							<a href="javascript:show('<?php echo $this->vars['objects'];?>',<?php echo $this->vars['description'][$i]['id'];?>);">Удл.</a>
						</td>
						
					</tr>
					<tr id="descInfo_<?php echo $this->vars['description'][$i]['id'];?>" >
						
					</tr>
					
				<?$i++;endwhile;?>
			</tbody>
		<?else :?>
			<tbody>
				<tr>
					<td colspan="3" style="text-align: center;">Нет данных</td>
					
				</tr>
			</tbody>
		<?endif;?>
    </thead>
</table>

<div class="modal hide fade" id="myModal">
    <div class="modal-header">
    <button class="close" data-dismiss="modal">×</button>
    <h3 id="link"></h3>
    </div>
    <div class="modal-body" id="modalTextIn" style="text-align: center;">
	<h4 style="padding: 5px 0 5px 0;">Вы действительно хотите удалить?</h4>
	<input type="hidden" id="id" />
	<input type="hidden" id="objects" />
    <button type="button" onclick="delDescription()" class="btn btn-primary">Удалить</button> 
	<button type="button" class="btn btn-primary" data-dismiss="modal">Отмена</button>
    </div>
    <div class="modal-footer">
    </div>
    </div>

<script>
function edit(obj,id) {
            
			$.get('/admin/editshow/obj/'+obj+'/id/'+id,
        function (html){			
			$('#descedit_'+id).html('<td><form id="updates2"  onsubmit="addEditDesc(\''+obj+'\'); return false;"><input type="hidden" name="act" value="upd"><input type="hidden" name="id" value="'+id+'"><textarea name="desc" rows="5" cols="40">'+html+'</textarea><br /><input type="submit" value="Добавить"></td></form>'); }
			,'html');
			
}

</script>

<script>
function addEditDesc(obj) {
				$.post(
				'/admin/description'+obj,
				$('#updates2').serialize(),
				function (html){
					window.location.href="/admin/description"+obj;
				},
				'html');
			}	

</script>		
	
<script>	
function show(objects,id)
{
	$('#myModal').modal('show');
	$('#id').val(id);
	$('#objects').val(objects);
}
</script>