<?php if($this->vars['elems']):?>
<table cellspacing="0" class="table table-striped table-bordered table-condensed">
<?php for($i=0;$i<count($this->vars['elems']);$i++):?>
	<tr id="found-<?php echo $this->vars['object'].'-'.$this->vars['elems'][$i]['id'];
		?>">
		<td ><img class="link" onclick="showFormInAllowd('<?php	echo $this->vars['object'];?>-<?php echo $this->vars['elems'][$i]['id'];?>')" 
		<?if($this->vars['elems'][$i]['allowed']==''):?>
			src="<?php echo $this->LoadResource('image','add.gif');?>" title="Добавить" style="padding:3px">
		<?else :?>
			src="<?php echo $this->LoadResource('image','b_edit.png');?>" title="Добавить">
		<?endif;?>	
		
		</td>
		<td><?php echo $this->vars['elems'][$i]['name'];?></td>
	</tr>
	<tr id="formsin_<?php echo $this->vars['object'].'-'.$this->vars['elems'][$i]['id']?>" style="display:none;">
		<td colspan="2">
			<?if($this->vars['elems'][$i]['allowed']==''):?>
			
				<form id="form-<?php echo $this->vars['object'].'-'.$this->vars['elems'][$i]['id']?>">отображать &nbsp; <select name="show_<?php echo $this->vars['object'].'-'.$this->vars['elems'][$i]['id']?>" >
						<option value="">(по умолчанию)</option>
						<option value="T">Да</option>
						<option value="F">Нет</option>
					</select>
					<input type="button" onclick="addAlowed('/admin/catalogEditDo/elem/<?php echo $this->vars['object']?>/id/<?=$this->vars['elems'][$i]['id']?>/act/add','<?php echo $this->vars['object'].'-'.$this->vars['elems'][$i]['id']?>');" value="OK">&nbsp;&nbsp;
					<input type="button" onclick="$('#formsin_<?php echo $this->vars['object'].'-'.$this->vars['elems'][$i]['id']?>').css('display','none');" value="Отмена">
				</form>
			<?else :?>
			 
				<form id="form-<?php echo $this->vars['object'].'-'.$this->vars['elems'][$i]['id']?>">
					отображать &nbsp; <select name="show_<?php echo $this->vars['object'].'-'.$this->vars['elems'][$i]['id']?>">
						<option value="">(по умолчанию)</option>
						<option value="T" <?if($this->vars['elems'][$i]['allowed']=="T"):?> selected<?endif;?>>Да</option>
						<option value="F" <?if($this->vars['elems'][$i]['allowed']=="F"):?> selected<?endif;?>>Нет</option>
					</select>&nbsp;&nbsp;
					<input type="button" onclick="addAlowed('/admin/catalogEditDo/elem/<?php echo $this->vars['object']?>/id/<?=$this->vars['elems'][$i]['id']?>/act/edit','<?php echo $this->vars['object'].'-'.$this->vars['elems'][$i]['id']?>');" value="OK">&nbsp;&nbsp;
					<input type="button" onclick="$('#formsin_<?php echo $this->vars['object'].'-'.$this->vars['elems'][$i]['id']?>').css('display','none');" value="Отмена">
				</form>
			<?endif;?>
			
		</td>
	</tr>
<?php endfor;?>
</table>
<?php else:?>
Ничего не найдено.
<?php endif;?>