<div class="page-header"> 
    <h2>История обновлений</h2>
    <small>С помощью данного раздела Вы сможете посмотреть, какие изменения были произведены в процессе обновления каталога.</small>
</div>
<?php echo $this->vars['paging']?>
<div class="container">
    <span>Обозначения: </span>
    <span class="badge badge-info">Изменено</span>
    <span class="badge badge-important">Удалено</span>
    <span class="badge badge-success">Добавлено</span>    
</div><br/>
<table class="table table-striped table-bordered table-condensed">
    <thead>
        <tr>
            <th width="10%" style="text-align: center;">Дата обновления</th>
            <th width="25%" colspan="3" style="text-align: center;">Товаров</th>
            <th width="25%" colspan="3" style="text-align: center;">Макетов</th>
			<th width="25%"  style="text-align: center;">Статус обновления</th>	
			<th width="25%"  style="text-align: center;">Детали</th>				
            
        </tr>
    </thead>
	<?for($i=0;$i<count($this->vars['of']);$i++):?>
		 <tr>     
			<td><?=date('d-m-Y G:i',$this->vars['of'][$i]['date']);?></td>
			<td style="text-align: right;"><span class="badge badge-info"><?=$this->vars['of'][$i]['info']['allOffersUp'][0]['cc']?></span></td>
            <td style="text-align: center;"><span class="badge  badge-important"><?=$this->vars['of'][$i]['info']['allOffersDel'][0]['cc']?></span></td>
            <td style="text-align: left;"><span class="badge badge-success"><?=$this->vars['of'][$i]['info']['allOffersAdd'][0]['cc']?></span></td>
			
            <td style="text-align: right;"><span class="badge badge-info"><? echo $this->vars['of'][$i]['info']['allMaketUp'][0]['cc'] ?></span></td>
            <td style="text-align: center;"><span class="badge  badge-important"><?=$this->vars['of'][$i]['info']['allMaketDel'][0]['cc']?></span></td>
            <td style="text-align: center;"><span class="badge badge-success"><?=$this->vars['of'][$i]['info']['allMaketAdd'][0]['cc']?></span></td>			
			
			<td style="text-align: center;;"><?if($this->vars['of'][$i]['status']==1):?>Успешно обновлено</td>
			<td style="text-align: center;;"><a href="/admin/historyitems/id/<?=$this->vars['of'][$i]['id']?>">Подробнее</td>		
			<?else :?>Ошибка обновления
			<td style="text-align: center;"><a href="javascript:void(0);" onclick="showError(<?=$this->vars['of'][$i]['id']?>);">Подробнее</td>
			
			<?endif;?>
			

                       

           
        </tr>
	<?endfor;?>
</table>
<div class="modal hide fade" id="myModal">
    <div class="modal-header">
    <button class="close" data-dismiss="modal">×</button>
    <h3 id="link"></h3>
    </div>
    <div class="modal-body" id="modalTextIn">
    
    </div>
    <div class="modal-footer">
    </div>
</div>
<script>
function showError(link)
{
	jQuery("#modalTextIn").html('<div style="width:100%;height:200px;background: url(\'/admin_tpl/images/loadinfo.net.gif\') center no-repeat;"></div>');
	jQuery("#link").html('');
	$('#myModal').modal('show');
	jQuery.ajax({
            type: "GET",
            url: '/admin/showerror/id/'+link,
            beforeSend: function() {
				jQuery("#loading").css('display','block');
				
            },
            complete: function(){
                    jQuery("#loading").css('display','none');
		},
            success: function(html){			
				
                jQuery("#loading").css('display','none');
				
				jQuery("#modalTextIn").html(html);
				jQuery("#link").html('Ошибка обновления');
               
               
            }

      });
	
	
}

</script>