<!DOCTYPE html>
<html>
    <head>
        <title>Администраторская панель</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="description" content="">
        <meta name="author" content="keepper">
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">

        <link href="/admin_tpl/styles/bootstrap.css"  rel="stylesheet">
        <style>
            body { padding-top: 60px; }
        </style>
        <link href="/admin_tpl/styles/bootstrap-responsive.css" rel="stylesheet">
        <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
        <!--[if lt IE 9]>
        <script src="/admin_tpl/scripts/ie-html5.js"></script>
        <![endif]-->
		<!--[if IE ]><link href="/admin_tpl/styles/bootstrap_ie.css" type="text/css" rel="stylesheet" /><![endif]-->
		<script src="/admin_tpl/scripts/jquery-1.3.2.min.js" ></script>
		<script src="/admin_tpl/scripts/script.js"></script>

        <style>
            .form-horizontal .control-label { width: 250px; }
            .form-horizontal .controls { margin-left: 270px; }
            .form-horizontal .form-actions { padding-left: 270px; }
            .form-horizontal legend {text-align: center; }
        </style>
		<script type="text/javascript" src="/admin_tpl/scripts/tiny_mce/tiny_mce.js"></script>         
<script type="text/javascript">
 function startTinyMCE(id){
		 tinyMCE.init({
		// General options
		mode : "exact",
		elements : id,
		theme : "advanced",
		plugins : "autolink,lists,pagebreak,style,layer,table,save,advhr,advimage,advlink,emotions,iespell,inlinepopups,insertdatetime,preview,media,searchreplace,print,contextmenu,paste,directionality,fullscreen,noneditable,visualchars,nonbreaking,xhtmlxtras,template,wordcount,advlist,autosave",

		// Theme options
		theme_advanced_buttons1 : "save,newdocument,|,bold,italic,underline,strikethrough,|,justifyleft,justifycenter,justifyright,justifyfull,|,link,unlink,image,cleanup,help,code,|,bullist,numlist,|,outdent,indent,blockquote,|,undo,redo,|,fontselect,fontsizeselect,forecolor",
		theme_advanced_buttons2 : "cut,copy,paste,pastetext,pasteword,|,search,replace,|,tablecontrols,|,hr,removeformat,visualaid",
		theme_advanced_buttons3 : "",
		theme_advanced_buttons4 : "",
		theme_advanced_toolbar_location : "top",
		theme_advanced_toolbar_align : "left",
		theme_advanced_statusbar_location : "bottom",
		theme_advanced_resizing : true,		
				
		// Style formats
		style_formats : [
			{title : 'Bold text', inline : 'b'},
			{title : 'Red text', inline : 'span', styles : {color : '#ff0000'}},
			{title : 'Red header', block : 'h1', styles : {color : '#ff0000'}},
			{title : 'Example 1', inline : 'span', classes : 'example1'},
			{title : 'Example 2', inline : 'span', classes : 'example2'},
			{title : 'Table styles'},
			{title : 'Table row 1', selector : 'tr', classes : 'tablerow1'}
		],

		// Replace values for the template plugin
		template_replace_values : {
			username : "Some User",
			staffid : "991234"
		},
				language : "ru"
	});
 }  
 
 function TabsIncorect()
{
	var hachNew='';	
	if(window.location.hash!='')
	{
		var m=window.location.hash.split('#');
			if(m[1])
				hachNew=m[1];
			$('#myTab a[href="#'+hachNew+'"]').tab('show');	
	}
}

/*function Remenu(arr)
{
	for(var i=0;i<all.length;i++)
	{
		$('#myTab a[href="#'+all[i]+'"]').tab('show');
	}
}*/
</script>

    </head>
    <body>
        <?php echo $this->vars['header'];?>
        <!-- /Основное меню -->
        <!-- Вывод предупреждений -->
		
			<?if(isset($_SESSION['is_admin'])):?>
				<div class="container">
				
					<?if($this->vars['catUpdate']['dates']!=0 and $this->vars['catUpdate']['dates']!=2):?>
						<div class="alert alert-error" id="messageAdmin">
							<strong>Внимание!</strong><br /> <span id="messageTxt">Доступно обновление каталога товаров от <?=$this->vars['catUpdate']['dates']?>. <a href="/admin/update">Обновить</a></span>
						</div>
					<?else :?>
						<div class="alert alert-error" id="messageAdmin" style="display:none;">
							<strong>Внимание!</strong><br /> <span id="messageTxt"></span>
						</div>
					<?endif?>	
				</div>
			<?endif;?>
		
        <!-- /Вывод предупреждений -->

        <!-- Контент страницы -->
        <div class="container" style="min-width: 940px;">
			<?php echo $this->vars['content'];?>
		</div>
        <!-- /Контент страницы -->
        <?php echo $this->vars['footer'];?>
		<script>
			TabsIncorect();
		</script>
		<div id="markhron" style="position:fixed;width:100%;height:100%;top:0px;left:0px;z-index:10000;display:none;"></div>
		<script>
			var version=navigator.userAgent.toLowerCase();			
			if(version.indexOf("opera")==0)
			{
				$('#myModal').removeClass('fade');				
			}
		</script>
    </body>
</html>