<script src="/admin_tpl/scripts/jquery.js"></script>
<style>
	table{width:100%;border: 1px solid #BDC6E0;}
	table td {
	font-size:12px;
	padding:2px;
	}
	table tr.h td{
	background: none repeat scroll 0 0 #F1F3FA;
    border-bottom: 1px solid #BDC6E0;
    border-right: 1px solid #BDC6E0;   
    text-align: center;
	}
	table tr.t td{
		border-right: 1px solid #BDC6E0;
		border-top: 1px solid #BDC6E0;    
		text-align: center;
	}
</style>
<div id="ins">
	
</div>
<div id="Load" style="width:100%;height:100px;background: url('/admin_tpl/images/loadinfo.net.gif') center no-repeat;">
	
</div>
<div style="margin-top:10px;font-size:11px;">Страница <?if($this->vars['all']>1):?>
<select onchange="show(this.value)">
	<?for($i=0;$i<$this->vars['all'];$i++):?>
		<option value="<?=($i+1)?>"><?=($i+1)?></option>
	<?endfor;?>
</select><?else:?>1<?endif;?> из <?=$this->vars['all']?></div>
<script>
	var pages=0;
	function showOne()
	{
		pages=1;
		$.post('/admin/showoffersadd',{page:pages},function(json){
			$('#ins').html(json.h);
			$('#Load').css('display','none');
		},"json");
		
		
	}
	function show(pageIn)
	{
		$('#ins').css('display','none');
		$('#Load').css('display','block');
		pages=pageIn;
		$.post('/admin/showoffersadd',{page:pages},function(json){
			$('#ins').html(json.h);
			$('#Load').css('display','none');
			$('#ins').css('display','block');
		},"json");
	}
	showOne();
</script>
