
<div class="page-header">
    <h2>SEO фичи</h2>
  
	    <div>Данный модуль предоставляет возможность модификации выводимых заголовков для разных страниц партнерского магазина.</div>
	    <div><br/>Для того, чтобы изменить заголовок, ключевые слова и описание для конкретной страницы, выполните следующие действия:</div>
	    <div>
	       <br/><strong>1).</strong> Откройте необходимую страницу вашего магазина. Например &quot;http://<?=$_SERVER['HTTP_HOST']?>/cat/104&quot;.
	       <br/><strong>2).</strong> Скопируйте URI данной страницы (ВНИМАНИЕ! Не путайте URI с URL). URI = URL - домен сайта. Например для страницы &quot;http://<?=$_SERVER['HTTP_HOST']?>/cat/104&quot; необходимо выбрать URI &quot;/cat/104&quot;
	       <br/><strong>3).</strong> Заполние поле &quot;Введите URI&quot; полученным значением (&quot;/cat/104&quot;) 
	       <br/><strong>4).</strong> Заполните поле &quot;Заголовок&quot;. Данное значение будет выводится в теге &lt;title&gt; для заданной страницы.
	       <br/><strong>5).</strong> Заполните поле &quot;Ключевые слова&quot;. Ключевые слова вводятся через запятую.
	       <br/><strong>6).</strong> Заполните поле &quot;Описание&quot;.
	       <br/><strong>7).</strong> Нажмите кнопку &quot;Добавить&quot;.
	    </div>
	
</div>
<div id="seo_fetaures_wrapper">
	<div style="float:left;width:30%;" >
		<div class="error"><?=$this->vars['warningText'];?></div>
		<div class="edit">
		<?php
		    if ( @$this->vars['id'] )
		    {
		    	echo "Редактирование правила #".$this->vars['id'];
		    }
		    $button_title = (@$this->vars['id']) ? 'Изменить' : 'Добавить';
		?>
		</div>
	    <form id="seo_f" onsubmit="return false;">
			
	        <input type="hidden" name="id" value="<?=@$this->vars['id']?>" />
			<table cellpadding="0"  cellspacing="0" class="table table-striped table-bordered table-condensed">
				<tr><td>
					<div >Введите URI:<span class="help">Например "/cat/104"</span></div><br/>				
					<input type="text" name="uri" value="<?=@$this->vars['rule']['uri']?>" />
				</td></tr>
				<tr><td>
				<div >Заголовок:<span class="help">&lt;TITLE&gt;</span></div><br/>
				<textarea name="title" rows="2" cols="40"><?=@$this->vars['rule']['title']?></textarea>
				</td></tr>
				<tr><td>
					<div >Ключевые слова:<span class="help">&lt;META name=&quot;keywords&quot;&gt;</span></div>
					<textarea name="keywords" rows="5" cols="40"><?=@$this->vars['rule']['keywords']?></textarea>
				</td></tr>
				<tr><td>
					<div >Описание:<span class="help">&lt;META name=&quot;description&quot;&gt;</span></div><br/>
					<textarea name="description" rows="5" cols="40"><?=@$this->vars['rule']['description']?></textarea>
				</td></tr>
				<tr><td>
					<input type="button" onclick="seoValid();" value="<?=$button_title?>" />
				</td></tr>
				
			</table>
	    </form>
	    
	</div>
	<div style="float:left;width:60%;margin-left:20px;">
	    <table class="table table-striped table-bordered table-condensed">
	            <tr class="heades">
	                <td>&nbsp;</td>
	                <td>ИД</td>
	                <td>URI</td>
	                <td>Заголовок</td>
	                <td>Keywords</td>
	                <td>Description</td>
	                <td>&nbsp;</td>
	            </tr>
	            <?php
	                foreach ( $this->vars['all_rules'] as $rule )
	                {
	                	echo "
	                	<tr class='lines'>
	                	   <td>
	                	       <img class=\"link\" title=\"Редактировать\" onclick=\"window.location.href='/admin/seo/id/{$rule['id']}'\" src=\"/admin_tpl/images/b_edit.png\">
	                	   </td>
	                	   <td>{$rule['id']}&nbsp;</td>
	                	   <td>{$rule['uri']}&nbsp;</td>
	                	   <td>{$rule['title']}&nbsp;</td>
	                	   <td>{$rule['keywords']}&nbsp;</td>
	                	   <td>{$rule['description']}&nbsp;</td>
	                	   <td>
	                           <img class=\"link\" title=\"Удалить\" onclick=\"show('{$rule['id']}');\" src=\"/admin_tpl/images/error.png\">
	                       </td>
	                	</tr>
	                	";
	                }
	            ?>
	    </table>
	</div>
	<div style="clear:both;"></div>
</div>

<div class="modal hide fade" id="myModal">
    <div class="modal-header">
    <button class="close" data-dismiss="modal">×</button>
    <h3 id="link"></h3>
    </div>
    <div class="modal-body" id="modalTextIn" style="text-align: center;">
	<h4 style="padding: 5px 0 5px 0;">Вы действительно хотите удалить?</h4>
	<input type="hidden" id="delSeoMainNah" />
    <button type="button" onclick="DelSeoRule()" class="btn btn-primary">Удалить</button> 
	<button type="button" class="btn btn-primary" data-dismiss="modal">Отмена</button>
    </div>
    <div class="modal-footer">
    </div>
    </div>

<script>	
function show(id)
{
	$('#myModal').modal('show');
	$('#delSeoMainNah').val(id);
}
</script>

<script>
function seoValid()
{
	var error=0;
	var errorText='';
	var uri=$('input[name="uri"]').val();
	var title=$('textarea[name="title"]').val();
	var keywords=$('textarea[name="keywords"]').val();
	var description=$('textarea[name="description"]').val();
	var reg=/([\<]+)/;
	var reg2=/([\>]+)/;
	if(uri=='')
	{
		error=1;
		errorText+='Введите "URI"';
	}
	else
	{
		
		if(reg.test(uri)) 
		{
			errorText+='Некорректный "URI" - символ < запрешен. \n';
			error=1;
		}
		else
		{
			if(reg2.test(uri))
			{
				errorText+='Некорректный "URI" - символ > запрешен. \n';
				error=1;
			}
		}
		
	}
	
	if(reg.test(title)) 
	{
		
		errorText+='Некорректный "Заголовок" -  символ < запрешен.\n';
		error=1;
	}
	else
	{
		if(reg2.test(title))
		{
			errorText+='Некорректный "Заголовок" - символ > запрешен. \n';
			error=1;
		}
	}
	if(reg.test(keywords)) 
	{
		errorText+='Некорректное поле "Ключевое слово" - символ < запрешен.\n';
		error=1;
	}
	else
	{
		if(reg2.test(keywords))
		{
			errorText+='Некорректное поле "Ключевое слово" - символ > запрешен. \n';
			error=1;
		}
	}
	if(reg.test(description)) 
	{
		errorText+='Некорректное поле "Описание" - символ < запрешен.\n';
		error=1;
	}
	else
	{
		if(reg2.test(description))
		{
			errorText+='Некорректное поле "Описание" - символ > запрешен. \n';
			error=1;
		}
	}
	
	
	
	if(error==0)
	{
		$.post('/admin/seo',$('#seo_f').serialize(),function(html){
			window.location.href="/admin/seo";
		})
	}	
	else
		alert(errorText);
}
</script>

