<script>

function DelsMenu(id)
{   
    if(!id)
	id=$('#delSeoMainNah').val();
	jQuery.ajax({
            type: "GET",
            url: '/admin/updatemenushow/act/del/id/'+id,
            success: function(html){
               
                      window.location.href="/admin/statmenu";

            }

      });
}
</script>

<div class="page-header">
    <h2>Пункты меню</h2>
    <small>Просмотр пунктов меню.</small>
</div>
<div class="topTile" style="margin: 0 auto;width: 109px;"> <?php echo @$this->vars['title'];?></div>
<div style="SHowInPAnel">
	<div style="margin-bottom:10px;"><a class="add" href="/admin/updatemenushow/act/add">Добавить пункт меню</a></div>
		<table class="table table-striped table-bordered table-condensed" >
			<tr class="heades">
				<td  width="40px"  >&nbsp;</td>
				<td  width="350px" >Название</td>
				<td  width="200px" >url</td>
				<td  width="40px"  ></td>
			</tr>
			<?php if(count($this->vars['allStat'])>0):?>
				<?php $i=0;while($i<count($this->vars['allStat'])):?>
				<tr class="params">
					<td  width="40px"  ><a href="/admin/updatemenushow/act/update/id/<?php echo $this->vars['allStat'][$i]['id'];?>"><img src="<?php echo $this->LoadResource('image','b_edit.png');?>"  title="Редактировать" class="link" /></a></td>
					<td  width="350px" ><?php echo $this->vars['allStat'][$i]['title'];?></td>
					<td  width="200px" ><?php echo $this->vars['allStat'][$i]['url'];?></td>
					<td  width="40px"  class="none"><img src="<?php echo $this->LoadResource('image','error.png');?>" onclick="show(<?php echo $this->vars['allStat'][$i]['id'];?>)" title="Удалить" class="link" /></td>
				</tr>
				<?php $i++;?>
				<?php endwhile;?>
			<?php else :?>
			<tr>
				<td style="font-size:13px;font-weight:bold;" align="center" colspan=4 class="row">Пунктов меню нет</td>
			</tr>
			 <?php endif;?>
		</table>
	</div>
	
<div class="modal hide fade" id="myModal">
    <div class="modal-header">
    <button class="close" data-dismiss="modal">×</button>
    <h3 id="link"></h3>
    </div>
    <div class="modal-body" id="modalTextIn" style="text-align: center;">
	<h4 style="padding: 5px 0 5px 0;">Вы действительно хотите удалить?</h4>
	<input type="hidden" id="delSeoMainNah" />
    <button type="button" onclick="DelsMenu()" class="btn btn-primary">Удалить</button> 
	<button type="button" class="btn btn-primary" data-dismiss="modal">Отмена</button>
    </div>
    <div class="modal-footer">
    </div>
    </div>

<script>	
function show(id)
{
	$('#myModal').modal('show');
	$('#delSeoMainNah').val(id);
}
</script>