<div class="page-header">
    <h2>Переходы с поисковиков</h2>
    <small>С помощью данного раздела Вы сможете посмотреть переходы с поисковиков.</small>
</div>
<div class="forms">
	<?=$this->vars['searchPanel']?>
</div>
<?$countAll=count($this->vars['allStat']);?>
<table class="table table-striped table-bordered table-condensed">
	<thead>
        <tr>
            <th width="25%" style="text-align: center;">Поисковая фраза</th>
            <th width="10%" style="text-align: center;">Поисковая система</th>
            <th width="10%" style="text-align: center;">Дата</th>
            <th width="10%" style="text-align: center;">Куда пришли</th>
            <th width="5%" style="text-align: center;">Кол-во заказанных товаров</th>
            <th width="5%" style="text-align: center;">Ссылка на заказ</th>
			<th width="15%" style="text-align: center;">Сессия</th>
           
        </tr>
		<?if($countAll>0):?>
			<tbody>
				<?php $i=0; while($i<$countAll) :?>
					<tr>
						<td style="text-align: center;"><?=$this->vars['allStat'][$i]['phrases']?></td>
						<td style="text-align: center;"><?=$this->vars['allStat'][$i]['system_search']?></td>
						<td style="text-align: center;"><?=date('d.m.Y G:i',$this->vars['allStat'][$i]['data'])?></td>
						<td style="text-align: center;"><?=$this->vars['allStat'][$i]['main_page']?></td>
						<td style="text-align: center;"><?=$this->vars['allStat'][$i]['count_zakaz']?></td>
						<td style="text-align: center;"></td>
						<td style="text-align: center;"><?=$this->vars['allStat'][$i]['session_id']?></td>											
					</tr>
				<?$i++;endwhile;?>
			</tbody>
		<?else :?>
			<tbody>
				<tr>
					<td colspan="7" style="text-align: center;">Нет данных</td>
					
				</tr>
			</tbody>
		<?endif;?>
    </thead>
</table>