<div class="contentTitle"><span>Шаг 2. Параметры соединения с базой данных</span></div><br/>
<div>
	<form action="/" method="POST">
		<table border="0">
		<tr>
			<td>Хост:</td>
			<td><input type="text" name="db_host" value="" /></td>
		</tr>
		<tr>
			<td>Название базы данных:</td>
			<td><input type="text" name="db_dbname" value="" /></td>
		</tr>
		<tr>
			<td>Логин пользователя:</td>
			<td><input type="text" name="db_user" value="" /></td>
		</tr>
		<tr>
			<td>Пароль пользователя:</td>
			<td><input type="password" name="db_pwd" value="" /></td>
		</tr>
		</table><br/>
		<input type="submit" name="submit" value="Проверить настройки и перейти на шаг 3 установки"/>
	</form>
</div>
