<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en" dir="ltr">

<head>
	<title>Магазин маек. Установка</title>	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
	<link href="/install/style/style.css" media="screen" rel="stylesheet" type="text/css" />
</head>
<body>

<div id="header"><span>Установка</span></div><br/>
<div id="message" class="message"></div>
<span class="correct_no"><?php echo @$vars['note']?></span><br/>

<?php require_once( $vars['stage'] ) ?>

</body>
</html>
