<div class="contentTitle"><span>Шаг 3. Партнерские параметры.</span></div><br/>
<div>
	<form action="/" method="POST">
		<table border="0">
		<tr>
			<td>Ref:</td>
			<td><input type="text" name="ref" value="" /></td>
		</tr>
		<tr>
			<td>SALT:</td>
			<td><input type="text" name="salt" value="" /></td>
		</tr>
		</table><br/>
		<input type="submit" name="submit" onclick="javascript: document.getElementById('message').innerHTML = 'Подождите, идет проверка...' "value="Проверить настройки и перейти на шаг 4 установки"/>
	</form>
</div>
